export const PHONE_NUMBER = '06 11 80 53 51'
export const POSTAL_CODE = '19310'
export const ADDRESS_LOCALITY = 'Louignac'
export const ADDRESS_COUNTRY = 'France'
export const ESTABLISHMENT_TITLE = 'Les cabanes de la Reynie'
